version: '0.0.2'
source: "https://github.com/HaXrBOT/ProcessedModTemplate/tree/master"
replacements:
  dependencies: ""
  fabric_dependencies: modApi ("me.shedaniel.cloth:cloth-config-fabric:${project.cloth_config_version}")
  forge_dependencies: implementation "maven.modrinth:cloth-config:${project.cloth_config_version}+forge"
  neoforge_dependencies: implementation "maven.modrinth:cloth-config:${project.cloth_config_version}+neoforge"
  mcpublish_dependencies: "cloth-config"
  licensename: "LICENSE"
  author: "HaXr"
  group: "dev.haxr"
  licenseName: "LGPL 3.0"
  description: "Prints information about the modpack into the logs & crash logs!"
  homepageUrl: "https://modrinth.com/mod/branded-logs"
  sourcesUrl: "https://github.com/HaXrBOT/Branded-Logs"
  issuesUrl: "https://github.com/HaXrBOT/Branded-Logs/issues"
  version: "2.0.3"
  breaks: ""
  name: "Branded Logs"
  id: "brandedlogs"
  fabric_entrypoint: "dev.haxr.brandedlogs.BrandedLogsMod"
  fabric_modmenu_entrypoint: "dev.haxr.brandedlogs.config.ModMenuIntegration"
  relocationpackage: "dev.haxr.brandedlogs"
  modrinthid: "tbktcZz2"
  curseforgeid: "882472"
  versionlessname: "BLVersionless"
  mcpublishVersion: "3.3.0"
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - modrinth
  - curseforge
rootProject:
  template: "."
subProjects:
  BLVersionless:
    template: "Versionless"
    replacements:
      dependencies: '
      compileOnly "com.google.code.gson:gson:2.10.1"

      compileOnly "org.apache.logging.log4j:log4j-core:2.20.0"
      '
